// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qldbsbscaiburbnvhcty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZGJzYnNjYWlidXJibnZoY3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NzIzNzAsImV4cCI6MjA1NjM0ODM3MH0.21-Jy6rNL_iXYmxp_ROMkdKMCf8q83iKXwiyYo1C9M0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);